# Generated by Django 3.2.12 on 2022-06-08 17:42

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0016_stock_quantity_allocated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0151_productchannellisting_product_pro_discoun_3145f3_btree'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('quantity', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('dest_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_warehouse', to='warehouse.warehouse')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.productvariant')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='transferrequest_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='transferrequest_meta_idx'),
        ),
    ]
