# Generated by Django 3.2.12 on 2022-06-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_nofification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrequest',
            old_name='product_id',
            new_name='product',
        ),
    ]
